### ISSUE TITLE
odd character in item description 

### ISSUE THREAD

**Issue by Tigerboy007** [SalvieMundi/DefinitiveEditionVanillaPlus#1]
strange charecter on the item description of the item 'Nether Eye
![2021-12-16_21 37 13](https://user-images.githubusercontent.com/96267009/146454388-64b2521b-061d-4472-a8f4-caafdea53d27.png)
'

**Comment by SalvieMundi** [comment]
I actually noticed this and corrected it, as well as made the descriptions less lengthy so they don't run across the entire screen. Somehow the fix must have gotten unfixed haha. Appreciate the report, will definitely look into it.

**Comment by Tigerboy007** [comment]
its also on the 'corrupted eye' item

**Comment by SalvieMundi** [comment]
finally figured this out. will be fixed in 1.0.7a
