### ISSUE TITLE
server down

### ISSUE THREAD

**Issue by marubucii** [SalvieMundi/DefinitiveEditionVanillaPlus#17]
server either crashed or temporarily went offline after being hit with slowness arrows a few times, may or may not be connected

**Comment by SalvieMundi** [comment]
Will check the server log in a day or two when I get back to working on this. Probably something with one of the MC Dungeon mods (sounds like a previous issue).

**Comment by SalvieMundi** [comment]
don't even see this crash in the logs. no crash logs. going to try reproducing by shooting a player with slowness arrows

**Comment by SalvieMundi** [comment]
after conversing with maru, appears this may just be #20, which deals with more general outages. attempted to get shot by skeletons with slowness arrows at the same mushroom structure, no repercussions. closing ticket to focus on #20.
