### ISSUE TITLE
barnacles

### ISSUE THREAD

**Issue by marubucii** [SalvieMundi/DefinitiveEditionVanillaPlus#18]
barnacles (outvoted) need to be a LOT rarer at the moment its literally impossible to traverse any ocean in a boat without getting stopped every minute. sometimes you'll encounter like five-seven in a row with no time to collect yourself

**Comment by SalvieMundi** [comment]
This should be easily fixable when I get back, just a matter of tweaking the setting down. It's interesting because I actually experienced the polar opposite of this problem during testing, where the thing just never seemed to spawn, so I turned the values way up...

OOOPPPS 😅

**Comment by SalvieMundi** [comment]
Set the spawn weight from 25 to 4 (the default is 2).

**Comment by SalvieMundi** [comment]
pushed change to server
