### ISSUE TITLE
server outages

### ISSUE THREAD

**Issue by marubucii** [SalvieMundi/DefinitiveEditionVanillaPlus#20]
im unsure if this is for a reason or not but i figured i would put it here anyway just in case lol 
occasionally the server will suddenly close and disconnect and wont be able to be connected to again for a while. it simply shows that it cant connect to the server and nothing else

**Comment by SalvieMundi** [comment]
I'll check the server logs. Sounds like something is causing a crash and the server usually takes about 5 to 10 minutes to auto reboot after a crash occurs. There will hopefully be extensive crash logs *he says, knowing this will almost undoubtedly be false*

**Comment by SalvieMundi** [comment]
*he says, knowing this will almost undoubtedly be false*

![image](https://user-images.githubusercontent.com/76707320/146655561-a18211c6-baf3-4211-938d-43b2fda21d0e.png)

The crash logs were a lie.

**Comment by SalvieMundi** [comment]
This is likely due to the problem found by tiger regarding Croptopia crashes.

**Comment by SalvieMundi** [comment]
Closing stale ticket with root cause likely fixed.
