### ISSUE TITLE
biome generation 

### ISSUE THREAD

**Issue by marubucii** [SalvieMundi/DefinitiveEditionVanillaPlus#22]
this isnt a bug, more of a suggestion(low priority) but in adventuring a lot ive found that especially with mods that add differing versions of these biomes combined with the original versions pretty much 90% of the world is either different kinds of forests or extreme mountains. Maybe it would be better to tweak generation to make other more unique biomes a bit more common? (like desert varieties for example)

**Comment by SalvieMundi** [comment]
Unsure if there's much I can do regarding biome placement, as it's really determined by a set of maps (temperature, humidity, randomness) that aren't currently very easy to modify without massively messing things up.

In all likelihood, we have a bad seed. Some seeds are ocean prone, some are desert prone, and some are plains heavy. We probably just have a very plains heavy seed. I will check to confirm or deny this tomorrow.

**Comment by SalvieMundi** [comment]
Here's a map preview of the current test server's seed: https://www.chunkbase.com/apps/seed-map#-6909076866056135041

![image](https://user-images.githubusercontent.com/76707320/146677923-23c0d82b-557e-4965-89ac-2c1690969b5a.png)

You'd have to travel over 2500+ blocks in any direction (closer to 4000+ considering distance in both planes -- x and z) to find a desert. Compare that to the very next seed that was randomly generated, where a desert is within 400 blocks of spawn if you move in the right direction: https://www.chunkbase.com/apps/seed-map#-3627363720727768054

![image](https://user-images.githubusercontent.com/76707320/146677963-6745d4d2-d00c-480d-b4b4-e4bdd6fdc69e.png)

Chalking this issue up to a bad seed, more of an issue with minecraft before mods.
