### ISSUE TITLE
items in holster slots disappear on death

### ISSUE THREAD

**Issue by Tigerboy007** [SalvieMundi/DefinitiveEditionVanillaPlus#25]

**Comment by SalvieMundi** [comment]
Must be mod incompatibility with Graves Not Forgotten. Might need to write the compatibility in myself.

**Comment by Tigerboy007** [comment]
if possible you could grab whatever code makes the artefact slots just drop on the ground?
wait... is that a bug?

**Comment by SalvieMundi** [comment]
Yeah, graves not forgotten is supposed to store all your stuff.

**Comment by SalvieMundi** [comment]
working on this...

**Comment by SalvieMundi** [comment]
problem appears to be solved for backslot and beltslot items. trinkets fall off player. dunno if that's ideal. might add compat for trinkets as well.

**Comment by SalvieMundi** [comment]
nevermind, trinkets looks god awful to try and make compatibility with. gonna wrap this up.
