### ISSUE TITLE
not sure how or why, but a  grave didnt spawn when I died

### ISSUE THREAD

**Issue by Tigerboy007** [SalvieMundi/DefinitiveEditionVanillaPlus#26]

**Comment by SalvieMundi** [comment]
Got the coords for that?

**Comment by Tigerboy007** [comment]
ah, not any more no I left the game

**Comment by Tigerboy007** [comment]
I can get aproximate ones?

**Comment by SalvieMundi** [comment]
Yes pls. :3

**Comment by Tigerboy007** [comment]
approximately 0, -17, 137

**Comment by Tigerboy007** [comment]
oh, and it was death by creeper if that matters

**Comment by SalvieMundi** [comment]
Might. Possibly, marker was blown up by the ensuing explosion.

**Comment by SalvieMundi** [comment]
According to the Server Log, marker spawned at y 11

[19:13:53] [Server thread/INFO]: [STDOUT]: [Markers] Marker spawned at: 0, 11, 136

**Comment by SalvieMundi** [comment]
Lines 99 - 101 of https://github.com/ginsm/notforgotten/blob/main/src/main/java/net/gleam/markers/Markers.java

`		if(blockPos.getY() < 0) {
			blockPos = new BlockPos(blockPos.getX(), 10, blockPos.getZ());
		}`
		
Likely done to prevent the void from filling with markers and creating a laggy server mess. However, 1.17 + Datapack onward will have a bottom of -64. Changing to this should fix:

`		if(blockPos.getY() < world.getBottomY()) {
			blockPos = new BlockPos(blockPos.getX(), world.getBottomY() + 10, blockPos.getZ());
		}`

**Comment by SalvieMundi** [comment]
fixed on my personal server, will commit up to github shortly

**Comment by Tigerboy007** [comment]
Ah! thanks!
