### ISSUE TITLE
I think I crashed the server by bonemealing an apple sappling?

### ISSUE THREAD

**Issue by Tigerboy007** [SalvieMundi/DefinitiveEditionVanillaPlus#29]

**Comment by Tigerboy007** [comment]
looks like it rebooted with a backup

**Comment by Tigerboy007** [comment]
did it again to check and it grew a single wood block and then I got a "connection lost" message

**Comment by Tigerboy007** [comment]
this was the 'apple sapling' from 'croptopia' to be precise

**Comment by SalvieMundi** [comment]
Took a couple tries, but I reproduced the issue. Looking into it now.

**Comment by SalvieMundi** [comment]
This is happening with all Croptopia saplings

**Comment by SalvieMundi** [comment]
This was due to an incompatibility with Straw Golem and Croptopia. Have informed both mod authors of my findings. For now, using a stop-gap solution for this modpack. Fix will be available in next update.
