### ISSUE TITLE
end portal glitch

### ISSUE THREAD

**Issue by marubucii** [SalvieMundi/DefinitiveEditionVanillaPlus#31]
slight visual bug when lighting end portals, the floor underneath will flicker through. this might just be me im not entirely sure

**Comment by SalvieMundi** [comment]
Legitimate issue with a fix, but not one I am likely to fix quickly due to being purely visual and impossible in survival (all naturally occurring end portals are set up above lava with no blocks below them).

**Comment by marubucii** [comment]
update: fixable by breaking the blocks underneath so a very minor problem

**Comment by SalvieMundi** [comment]
fixed in next update
