### ISSUE TITLE
end saddle glitch

### ISSUE THREAD

**Issue by marubucii** [SalvieMundi/DefinitiveEditionVanillaPlus#32]
trying to bring a mount through an end portal will cause the saddle on it to disappear 
(ps it doesnt work lol theyre all too big)

**Comment by SalvieMundi** [comment]
Will look into, likely won't fix due to being admittedly impossible in survival. Assuming this is the Enderwhale, it's likely an intentional decision by Globox. If it's regarding the dragon, I don't have source code for Mythic Mounts and can't obtain it.

**Comment by SalvieMundi** [comment]
Closing issue as I can't fix the dragon even if I wanted to. Also believe this is a non-issue in survival.
