### ISSUE TITLE
void blossom health bar is visible from surface

### ISSUE THREAD

**Issue by Tigerboy007** [SalvieMundi/DefinitiveEditionVanillaPlus#52]

**Comment by SalvieMundi** [comment]
Unfortunately, this actually is vanilla gameplay behavior, and the BOMD mod doesn't attempt to address the behavior except by ensuring that the void blossom only spawns once the player is within a certain block radius of it's boss room. This could be remedied in net.minecraft.entity.boss.ServerBossBar (totally guessing), but seeing as this deals with networking and I would essentially be making a new, separate mod on my own, I'm going to call this a "won't fix" type of issue.
