### ISSUE TITLE
new colours of Axolotle dont show up as their colour in the buckets

### ISSUE THREAD

**Issue by Tigerboy007** [SalvieMundi/DefinitiveEditionVanillaPlus#55]
this may be hard to fix as there'll be no texture for them,  if you ant I could try make some textures for them? not sure how good they'll be but I can try?

**Comment by Tigerboy007** [comment]
it seems that none of them are working?

**Comment by SalvieMundi** [comment]
more axolotl variants mod and axolotl bucket fix mod should work together to solve this issue for all colors of axolotl -- vanilla and modded. Will look into more. Likely to be a quick fix.

**Comment by SalvieMundi** [comment]
issue appears to be with implementation used to replace vanilla models. mod itself is injecting nbt tags as it should. likely going to have to make adjustments to the way model replacement works. fun

**Comment by SalvieMundi** [comment]
fixed. will be available next update.
