### ISSUE TITLE
Gobber bows dont consume arrows when used with the quivers

### ISSUE THREAD

**Issue by Tigerboy007** [SalvieMundi/DefinitiveEditionVanillaPlus#56]
I totally forgot to post this one, the arrow can be picked up after its shot, making this a way to get infinite of any arrows

**Comment by SalvieMundi** [comment]
dreading looking into this but it definitely needs fixing.

**Comment by SalvieMundi** [comment]
fixed. gobber needlessly overrode a bow method, but the overridden version provided by gobber is exactly the same as the original vanilla method. So just removed the overridden method, and then the bow uses the vanilla method, which is modified by nyf's quivers.
