### ISSUE TITLE
Elytrats

### ISSUE THREAD

**Issue by marubucii** [SalvieMundi/DefinitiveEditionVanillaPlus#59]
Putting an elytrat on a rat causes it (the rat and the elytrat both) to lose texture and display the purple and black texture not found colours

**Comment by SalvieMundi** [comment]
which rat? will any rat do this? Cannot reproduce the bug.

**Comment by SalvieMundi** [comment]
Confirmed this happens with named special rats like hat kid

**Comment by SalvieMundi** [comment]
https://github.com/Ladysnake/Rats-Mischief/commit/936281da05b9adeb222b6a4b29400b5ba46327bd

**Comment by SalvieMundi** [comment]
don't want to go through process of backporting to 1.17.1. Just going to move the elytrat textures where the mod is looking for them. will check to see if issue resolves soon.

**Comment by SalvieMundi** [comment]
indeed fixed
