### ISSUE TITLE
Gobbler lucky ore 

### ISSUE THREAD

**Issue by marubucii** [SalvieMundi/DefinitiveEditionVanillaPlus#60]
Mining the gobber lucky ore causes it to break with no particles or sound, just suddenly disappear. It still drops its items

**Comment by SalvieMundi** [comment]
confirmed issue. Lessened if physics mod is turned on, and is probably why I never noticed. this may stay left open if it isn't a quick fix, as I already have a lot of fixes to do.

**Comment by SalvieMundi** [comment]
fixed. will be in next update
